### ISSUE TITLE
Add Support for Solr 5.5 , support for SolrCloud Env

### ISSUE THREAD

**Issue by vlingadal** [sematext/solr-researcher#2]
Solr 5.5 version with embedded zookeeper in a SolrCloud environment fails with NPE in a relaxer component.  Issue seems to be related to ResearchHandler.isDistributed not able to access/set org.apache.solr.handler.component.ResponseBuilder:SolrRequestInfo and boolean isDistrib; parameters.
Caused by: java.lang.NullPointerException
        at org.apache.solr.common.util.StrUtils.splitSmart(StrUtils.java:90)
        at org.apache.solr.handler.component.HttpShardHandlerFactory.makeURLList(HttpShardHandlerFactory.java:256)
        at org.apache.solr.handler.component.HttpShardHandler.getURLs(HttpShardHandler.java:120)
        at org.apache.solr.handler.component.HttpShardHandler.submit(HttpShardHandler.java:161)
        at org.apache.solr.handler.component.ShardHandler.submit(ShardHandler.java:23)
        at com.sematext.solr.handler.component.ReSearcherHandler.handleSuggestionRequest(ReSearcherHandler.java:149)
        at com.sematext.solr.handler.component.ReSearcherHandler.handleSuggestionHitsRequest(ReSearcherHandler.java:45)
        at com.sematext.solr.handler.component.relaxer.QueryRelaxerComponent.doProcess(QueryRelaxerComponent.java:136)

**Comment by otisg** [comment]
Unfortunately, I think we won't be adding support for Solr 5.x.

**Comment by kimberlad** [comment]
Is this issue solved in a more recent version of SolrCloud? The Support matrix doesn't really clarify.

**Comment by otisg** [comment]
I don't recall a fix explicitly aimed at that, but your best bet is to give it a whirl.

**Comment by kimberlad** [comment]
So do sematext not use this project and or Solr Cloud in their Cloud offering? i.e. has this project been put out to "pasture"?

**Comment by otisg** [comment]
Sematext Cloud offers monitoring, log management, etc., not Solr.
We do use ReSearcher with Solr 7 on e.g. http://search-lucene.com/ so ReSearcher does work.  Maybe the issue here is the *embedded* ZK, which we don't use.

**Comment by kimberlad** [comment]
Thanks for the clarification, it really helps.

**Comment by kimberlad** [comment]
"We do use ReSearcher with Solr 7"
Apologies follow up question I've been asked
Does that deployment utilise "collections spanning multiple shards"?

**Comment by otisg** [comment]
In our case it does not.
