### ISSUE TITLE
Support for Solr 6.6.0

### ISSUE THREAD

**Issue by sandeepdas** [sematext/solr-researcher#3]
Getting the following exception 

Caused by: org.apache.solr.common.SolrException: Error Instantiating searchComponent, com.sematext.solr.handler.component.dym.DymReSearcher failed to instantiate org.apache.solr.handler.component.SearchComponent
       at org.apache.solr.core.SolrCore.<init>(SolrCore.java:977)
       at org.apache.solr.core.SolrCore.<init>(SolrCore.java:830)
       at org.apache.solr.core.CoreContainer.create(CoreContainer.java:920)
       ... 7 more
Caused by: org.apache.solr.common.SolrException: Error Instantiating searchComponent, com.sematext.solr.handler.component.dym.DymReSearcher failed to instantiate org.apache.solr.handler.component.SearchComponent
       at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:774)
       at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:133)
       at org.apache.solr.core.PluginBag.init(PluginBag.java:269)
       at org.apache.solr.core.PluginBag.init(PluginBag.java:258)
       at org.apache.solr.core.SolrCore.loadSearchComponents(SolrCore.java:1740)
       at org.apache.solr.core.SolrCore.<init>(SolrCore.java:929)
       ... 9 more
Caused by: java.lang.ClassCastException: class com.sematext.solr.handler.component.dym.DymReSearcher
       at java.lang.Class.asSubclass(Class.java:3404)
       at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:540)
       at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:487)
       at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:753)

**Comment by otisg** [comment]
Did you use ReSearcher with a different/older version of Solr and it worked until you upgraded Solr?

**Comment by sandeepdas** [comment]
Trying it on 6.6.0 version.   tried initializing SearchComponent Object using the com.sematext.solr.handler.component.dym.DymReSearcher class

```
<searchComponent name="dymReSearcher"
  class="com.sematext.solr.handler.component.dym.DymReSearcher">
    <int name="maxOriginalResults">0</int>
    <int name="maxOriginalResultsToReturnResults">5</int>
    <int name="suggestionsToReturn">5</int>
    <int name="minResultsForAcceptableSuggestion">3</int>
    <float name="minRequiredSuggestionRatio">0.0</float>
</searchComponent>
```

**Comment by otisg** [comment]
What do these numbers represent?

**Comment by manojpant** [comment]
@otisg We didnot use ReSearcher with an older version of Solr. We currently building this in Solr 6.6.0.
And the above numbers are just an example of your search component.
Even we comment out these int and float part still this error exist.

**Comment by nmtien** [comment]
Upgraded to Solr 6.6.0

**Comment by otisg** [comment]
Reopening until we publish to Maven, @nmtien.

**Comment by nmtien** [comment]
publish to Maven
https://oss.sonatype.org/content/repositories/releases/com/sematext/solr/st-ReSearcher-core/1.12.6.6.0/

**Comment by manojpant** [comment]
@nmtien Still getting the same error.
