### ISSUE TITLE
Getting Index out of bound while configuring solr 6.6.0 with DYM ReSearcher 

### ISSUE THREAD

**Issue by manojpant** [sematext/solr-researcher#4]
**Getting the below error while configuring solr 6.6.0 with DYM ReSearcher:**

Caused by: java.lang.IndexOutOfBoundsException: Index: 9, Size: 8
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at org.apache.solr.common.util.NamedList.getVal(NamedList.java:175)
at com.sematext.solr.handler.component.ReSearcherUtils.iterateOverSpellcheckerSuggestionsForWord(ReSearcherUtils.java:109)
at com.sematext.solr.handler.component.dym.DymReSearcher.createSuggestions(DymReSearcher.java:376)
at com.sematext.solr.handler.component.dym.DymReSearcher.doProcess(DymReSearcher.java:195)
at com.sematext.solr.handler.component.AbstractReSearcherComponent.doProcess(AbstractReSearcherComponent.java:172)

**Spell suggestions are coming.**

**Query that I fired is 
select/q=appel&spellcheck=true&spellcheck.onlyMorePopular=true&spellcheck.count=3&DymReSearcher=true**

**If I add spellcheck.extendedResults=true in the above query its directly giving the error, without giving spellcheck suggestions.**
**Giving the below error** 

Caused by: java.lang.IllegalAccessError: tried to access field org.apache.solr.handler.component.ResponseBuilder.isDistrib from class org.apache.solr.handler.comp
onent.ReSearcherHandler
        at org.apache.solr.handler.component.ReSearcherHandler.handleSuggestionRequest(ReSearcherHandler.java:171)
        at org.apache.solr.handler.component.ReSearcherHandler.handleSuggestionHitsRequest(ReSearcherHandler.java:60)
        at com.sematext.solr.handler.component.dym.DymReSearcher.doProcess(DymReSearcher.java:231)
        at com.sematext.solr.handler.component.AbstractReSearcherComponent.doProcess(AbstractReSearcherComponent.java:172)
        at com.sematext.solr.handler.component.AbstractReSearcherComponent.process(AbstractReSearcherComponent.java:130)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:296)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
        at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:723)
        at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:529)

**Comment by manojpant** [comment]
This issue is resolved. I am able to fetch suggestions but not results(documents) based on the suggestion as per the description below.

_Not only does DYM ReSearcher pick better suggestions than Solr Spellchecker, it also immediately queries Solr and delivers the results for the corrected query composed using the best suggested term(s) without the client having to do any extra work_.

Can you please help me to figure out if I have missed some configurations?

**Comment by sandeepdas** [comment]
Failing to understand why would 
java.lang.IllegalAccessError occur
when code is trying to access field org.apache.solr.handler.component.ResponseBuilder.isDistrib from class org.apache.solr.handler.component.ReSearcherHandler when both the classes are the same package

is it due to "same package" but different JARS?

**Comment by sandeepdas** [comment]
both the JARS along with solr core should be loaded from the same location, then it works
